[Engine]
EnableAudio = true
EnableVideo = true
# 发布流默认过期时间单位秒
PublishTimeout = 60

[Summary]
# 1秒中采样一次
SampleRate = 5

[RTMP]
ListenAddr = "127.0.0.1:1935"

[GateWay]
ListenAddr = "127.0.0.1:8080"

#ListenAddrTLS = "127.0.0.1:8082"
#CertFile = "xxx.cert"
#KeyFile = "xxx.key"
[Jessica]

#ListenAddr = "127.0.0.1:8081"
#ListenAddrTLS = "127.0.0.1:8083"
#CertFile = "xxx.cert"
#KeyFile = "xxx.key"
[LogRotate]
# 日志存储目录相对或绝对
Path = "logs"
# 日志是否按大小分割，0表示不按大小分割，非零代表按该大小字节进行分割
Size = 0
Days = 1
# 按照go layout格式化，默认按照小时
Formatter = "2006-01-02T15"

[Cluster]
# 监听端口代表该服务器为源服务器
ListenAddr = "127.0.0.1:2019"

# 源服务器地址，用于向源服务器进行推或拉流
#OriginServer = ""
[HLS]
# 是否开启写磁盘，开启后侦测到发布流就会开始写TS文件
EnableWrite = false
# 是否打开内存模式，在内存中保留TS数据，方便直接读取
EnableMemory = false
# 分片大小 单位秒
Fragment = 10
# 窗口数里，代表一个m3u8文件里面有几个ts
Window = 2
# ts文件存放目录，m3u8会存放在上一级
Path = "resource"

[HDL]

#ListenAddr = "127.0.0.1:2020"
#ListenAddrTLS = "127.0.0.1:2021"
#CertFile = "xxx.cert"
#KeyFile = "xxx.key"
[TS]
# ts存放目录
Path = "resource"

[Record]
Path = "resource"
# 自动录制功能
AutoRecord = false

[RTSP]
# 端口接收推流
ListenAddr = "127.0.0.1:554"
Reconnect = true

#启动后自动拉流，可以配置多个
#[RTSP.AutoPullList]
#"live/rtsp2" = "rtsp://admin:admin@192.168.1.212:554/cam/realmonitor?channel=1&subtype=1"
[WebRTC]

# 端口范围不配置的话是自动分配
# PortMin = 30000
# PortMax = 40000
# 公网访问必须配置PublicIP，否则无法建立连接
# PublicIP = ["192.168.1.120"]
# WebRTC 推流时控制GOP大小，单位毫秒
# PLI = 2000
[GB28181]
Serial = "34020000002000000001"
Realm = "3402000000"
Expires = 3600
ListenAddr = "127.0.0.1:5060"
# 自动停止发布，当订阅者数量将为0时，自动断开
AutoUnPublish = true
# 自动拉流，如果开启，则拿到设备注册信息后，就从设备拉流
AutoInvite = false
